Rapper.create!(name: "Vince Staples", album_sales: 1 , fire: true )
Rapper.create!(name: "Nas", album_sales: 1000000, fire: true )
Rapper.create!(name: "Matty B", album_sales: 1 , fire: false )
Rapper.create!(name: "Bushwick Bill", album_sales: 5000, fire: true )
Rapper.create!(name: "Missy Elliott", album_sales: 1000000 , fire: true )
Rapper.create!(name: "Lauryn Hill", album_sales: 2000000 , fire: true )
Rapper.create!(name: "Dylan", album_sales: 0 , fire: false )
Rapper.create!(name: "Rico Nasty", album_sales: 0 , fire: true )
